// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgHShmNZzIx0CnICTQFuwFNvCHIHVg-vE',
    appId: '1:359044198557:web:5a80577cbd4abbbeb96474',
    messagingSenderId: '359044198557',
    projectId: 'bitetime-f237a',
    authDomain: 'bitetime-f237a.firebaseapp.com',
    storageBucket: 'bitetime-f237a.firebasestorage.app',
    measurementId: 'G-8SHS6YZ6TB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABtsr0m9mt6fHSvF2bXGm3s7RI9vTXx2c',
    appId: '1:359044198557:android:35b8aa4e5aad13f1b96474',
    messagingSenderId: '359044198557',
    projectId: 'bitetime-f237a',
    storageBucket: 'bitetime-f237a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATxfyCMdSVzinrSw9dtqQaefJhQSdcWgY',
    appId: '1:359044198557:ios:ec3d5f25ec0c4d74b96474',
    messagingSenderId: '359044198557',
    projectId: 'bitetime-f237a',
    storageBucket: 'bitetime-f237a.firebasestorage.app',
    iosBundleId: 'com.example.bitetime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAxhSmvUWqY3r2g36DRR1RjzsvHv775gSk',
    appId: '1:88068859744:ios:27492927af788800472005',
    messagingSenderId: '88068859744',
    projectId: 'bitetime-6d9e3',
    storageBucket: 'bitetime-6d9e3.firebasestorage.app',
    iosBundleId: 'com.example.bitetime',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgHShmNZzIx0CnICTQFuwFNvCHIHVg-vE',
    appId: '1:359044198557:web:51c5a364f90c6862b96474',
    messagingSenderId: '359044198557',
    projectId: 'bitetime-f237a',
    authDomain: 'bitetime-f237a.firebaseapp.com',
    storageBucket: 'bitetime-f237a.firebasestorage.app',
    measurementId: 'G-K511C39BZG',
  );

}